platform:ios,'7.0'
pod 'Reachability','~>3.1.1'
pod 'ZipArchive','~>1.2.0'
pod 'AFNetworking','~>2.2.3'
pod 'SSAppURLs','~>0.0.7'
link_with 'Protoshop','Protoshop For AdHoc','Protoshop For AppStore'

# Remove 64-bit build architecture from Pods targets
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ARCHS'] = '$(ARCHS_STANDARD_32_BIT)'
    end
  end
end